import os
from typing import Annotated, TypedDict, List
from operator import add

from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage, SystemMessage, ToolMessage
from langgraph.graph import StateGraph, END

# --- 1. Define the State ---
class AgentState(TypedDict):
    # 'add' ensures that new messages are appended to the list rather than overwriting it
    messages: Annotated[List[BaseMessage], add]

class InvestigatorAgent:
    def __init__(self, model: ChatOpenAI, tools: list, system_prompt: str = ""):
        """
        Initializes the autonomous agent with a graph-based reasoning loop.
        
        Args:
            model: An instance of ChatOpenAI.
            tools: A list of @tool decorated functions (from tools.agent_tools).
            system_prompt: The persona/instructions for the agent.
        """
        self.system = system_prompt
        # Map tools by name for easy lookup during the 'action' phase
        self.tools = {t.name: t for t in tools}
        
        # Bind tools to the model to enable OpenAI Tool Calling
        self.model = model.bind_tools(tools)

        # --- 2. Build the Graph ---
        builder = StateGraph(AgentState)

        # Define Nodes
        builder.add_node("llm", self.call_llm)
        builder.add_node("action", self.take_action)

        # Set Entry Point
        builder.set_entry_point("llm")
        
        # Define Conditional Edges (The "Brain" decides whether to act or finish)
        builder.add_conditional_edges(
            "llm",
            self.should_continue,
            {True: "action", False: END}
        )

        # Define Normal Edges (Action always leads back to LLM for review)
        builder.add_edge("action", "llm")

        # Compile the Graph
        self.graph = builder.compile()

    # --- 3. Node & Edge Logic ---

    def should_continue(self, state: AgentState):
        """Logic for the conditional edge: Check if the LLM generated tool calls."""
        last_message = state['messages'][-1]
        return len(last_message.tool_calls) > 0

    def call_llm(self, state: AgentState):
        """The Reasoning Node: Calls GPT-4o with the current conversation state."""
        messages = state['messages']
        if self.system:
            messages = [SystemMessage(content=self.system)] + messages
        
        response = self.model.invoke(messages)
        return {"messages": [response]}

    def take_action(self, state: AgentState):
        """The Execution Node: Runs the tools requested by the LLM."""
        last_message = state['messages'][-1]
        tool_results = []

        for tool_call in last_message.tool_calls:
            print(f"🛠️ Executing: {tool_call['name']}...")
            
            if tool_call['name'] not in self.tools:
                result = f"Error: Tool '{tool_call['name']}' not found."
            else:
                # Invoke the tool with arguments generated by the LLM
                result = self.tools[tool_call['name']].invoke(tool_call['args'])
            
            # Feed the result back as a ToolMessage
            tool_results.append(
                ToolMessage(
                    tool_call_id=tool_call['id'],
                    name=tool_call['name'],
                    content=str(result)
                )
            )
        
        return {"messages": tool_results}